"""add_workflow_graph_to_session


Revision ID: f8555dcd9ac2
Revises: 705b40bb38ad
Create Date: 2026-08-27 07:24:23.126417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8555dcd9ac2'
down_revision: Union[str, Sequence[str], None] = '705b40bb38ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('workflow_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'workflow_graph')
    op.drop_index(op.f('ix_memory_entries_id'), table_name='memory_entries')
    op.create_index(op.f('memory_entries_embedding_idx'), 'memory_entries', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
